### ISSUE TITLE
Sup the upload section not working

### ISSUE THREAD

**Issue by qorahoja** [aniko33/Charles-CSEC#3]
When i try upload some txt file i got that error

Exception in thread Thread-2 (write):
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000022EB26A1900>: Failed to resolve 'api.anonfiles.com' ([Errno 11001] getaddrinfo failed)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Администратор\Desktop\Charles-CSEC\client\main.py", line 231, in write
    upload = anon.upload(msg_splited[1], progressbar=False)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\anonfile\anonfile.py", line 302, in upload
    response = self.session.post(
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 449, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'tuple' and 'int'

pls help someone

**Comment by NullyIsHere** [comment]
@aniko33 Sorry for ping.

**Comment by aniko33** [comment]
the problem is anonfile's (unofficial) bees are now unsupported, this project at the moment I'm not continuing it, I think in the next few months I will decide to change it. thanks for the report
